apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.26.0-rc.8c23dc4
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.32.0-rc.96ac49b
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.10.6-rc3
