apiVersion: v2
dependencies:
- name: kubefirst-pro-api
  repository: https://charts.konstruct.io
  version: 0.1.0-rc.f262b91
- name: kubefirst-pro-ui
  repository: https://charts.konstruct.io
  version: 0.1.0-rc.bb550ed
description: kubefirst pro helm chart
name: kubefirst-pro
type: application
version: 2.6.2-rc8
