apiVersion: v2
dependencies:
- name: colony-push-agent
  repository: https://charts.kubefirst.com
  version: 0.1.0-rc.bec62b3
- name: colony-pull-agent
  repository: https://charts.kubefirst.com
  version: 0.1.0-rc.3459331
description: kubefirst helm chart
name: colony
type: application
version: 0.1.0-rc21
