apiVersion: v2
dependencies:
- name: colony-agent
  repository: https://charts.konstruct.io
  version: 0.9.0-rc.0adc915
description: Colony helm chart
name: colony
type: application
version: 0.0.5-rc1
