apiVersion: v2
dependencies:
- name: colony-agent
  repository: https://charts.kubefirst.com
  version: 0.1.3-rc.1a66185
description: kubefirst helm chart
name: colony
type: application
version: 0.1.0-rc115
