apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  entrypoint: main
  serviceAccountName: argo-server
  templates:
    - name: main
      steps:
        - - name: checkout
            templateRef:
              name: cwft-git
              template: checkout-with-gitops-for-charts
              clusterScope: true
            arguments:
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: branch
                  value: '{{workflow.parameters.branch}}'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'
        - - name: get-macro-chart-version
            templateRef:
              name: cwft-helm
              template: get-macro-chart-version-from-gitops-repo
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: gitopsSourceFile
                  value: 'registry/{{workflow.parameters.clusterName}}/components/staging/kubefirst.yaml' #hardcoded env
        - - name: get-release-version-from-rc
            templateRef:
              name: cwft-helm
              template: get-release-version-from-rc
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: rcVersion
                  value: '{{steps.get-macro-chart-version.outputs.result}}'
        - - name: set-macro-chart-version
            templateRef:
              name: cwft-helm
              template: set-macro-chart-version
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: chartDir
                  value: 'charts/kubefirst'
                - name: chartVersion
                  value: '{{steps.get-release-version-from-rc.outputs.result}}'
        - - name: commit-release-chart-increment
            templateRef:
              name: cwft-git
              template: pull-commit-push
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-macro-chart-version.outputs.artifacts.repo-source}}'
              parameters:
                - name: repoName
                  value: '{{workflow.parameters.appName}}'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'
                - name: commitMessage
                  # Please, be careful updating this message, it must comply with:
                  # github skip ci rule: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
                  # github skip ci rule: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
                  # gitlab skip ci rule: https://devops.stackexchange.com/questions/6809/is-there-a-ci-skip-option-in-gitlab-ci
                  # in case, the rule is disbaled or don't work this step will create a circular trigger of builds and bumps of version.
                  value: "[skip ci] [CI SKIP] setting kubefirst chart to release version {{steps.get-release-version-from-rc.outputs.result}}\n\nskip-checks:true"
        - - name: publish-helm-chart
            templateRef:
              name: cwft-helm
              template: publish-chart
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-macro-chart-version.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: chartDir
                  value: 'charts/kubefirst'
        - - name: release-and-tag-main-with-notes
            templateRef:
              name: cwft-git
              template: release-and-tag-main-with-notes
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-macro-chart-version.outputs.artifacts.repo-source}}'
              parameters:
                - name: orgName
                  value: 'kubefirst'
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: tagName
                  value: 'v{{steps.get-release-version-from-rc.outputs.result}}'
        - - name: increment-chart-minor
            templateRef:
              name: cwft-helm
              template: increment-chart-minor
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-macro-chart-version.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: chartDir
                  value: 'charts/kubefirst'
                - name: chartVersion
                  value: '{{steps.get-release-version-from-rc.outputs.result}}'

        - - name: commit-bumped-version-
            templateRef:
              name: cwft-git
              template: pull-commit-push
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.increment-chart-minor.outputs.artifacts.repo-source}}'
              parameters:
                - name: repoName
                  value: '{{workflow.parameters.appName}}'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'
                - name: commitMessage
                  # Please, be careful updating this message, it must comply with:
                  # github skip ci rule: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
                  # github skip ci rule: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
                  # gitlab skip ci rule: https://devops.stackexchange.com/questions/6809/is-there-a-ci-skip-option-in-gitlab-ci
                  # in case, the rule is disbaled or don't work this step will create a circular trigger of builds and bumps of version.
                  value: "[skip ci] [CI SKIP] bumping kubefirst chart to chart version {{steps.get-release-version-from-rc.outputs.result}}\n\nskip-checks:true"
