apiVersion: v2
dependencies:
  - name: console
    repository: https://charts.kubefirst.com
    version: 2.33.0
  - name: kubefirst-api
    repository: https://charts.kubefirst.com
    version: 0.60.0-rc.6220a61
  - name: mongodb
    condition: mongodb.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 13.10.3
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.2.11-rc.1
