apiVersion: v2
dependencies:
  - name: console
    repository: https://charts.kubefirst.com
    version: 2.40.0-rc.d7cad5c
  - name: kubefirst-api
    repository: https://charts.kubefirst.com
    version: 0.66.0-rc.b95b577
  - name: kubefirst-api-ee
    repository: https://charts.kubefirst.com
    version: 0.3.0-rc.11eb3ca
  - name: mongodb
    condition: mongodb.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 13.10.3
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.3.0-rc27
