apiVersion: v2
dependencies:
- name: console
  repository: https://charts.kubefirst.com
  version: 2.42.0-rc.1ee844e
- name: kubefirst-api
  repository: https://charts.kubefirst.com
  version: 0.73.0-rc.e2bdc83
- name: kubefirst-api-ee
  repository: https://charts.kubefirst.com
  version: 0.5.0-rc.a392a3e
- condition: mongodb.enabled
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 13.10.3
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.3.6-rc66
