apiVersion: v2
dependencies:
- name: console
  repository: https://charts.kubefirst.com
  version: 2.44.0
- name: kubefirst-api
  repository: https://charts.kubefirst.com
  version: 0.77.0
- name: kubefirst-api-ee
  repository: https://charts.kubefirst.com
  version: 0.7.0
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.4.0
