apiVersion: v2
dependencies:
- name: console
  repository: https://charts.kubefirst.com
  version: 2.45.0-rc.f0feabc
- name: kubefirst-api
  repository: https://charts.kubefirst.com
  version: 0.82.0-rc.1c6906e
- name: kubefirst-api-ee
  repository: https://charts.kubefirst.com
  version: 0.8.0
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.4.4-rc8
