apiVersion: v2
dependencies:
- name: console
  repository: https://charts.kubefirst.com
  version: 2.40.0-rc.631020d
- name: kubefirst-api
  repository: https://charts.kubefirst.com
  version: 0.70.0-rc.848b645
- name: kubefirst-api-ee
  repository: https://charts.kubefirst.com
  version: 0.5.0-rc.6ae1d09
- name: mongodb
  condition: mongodb.enabled
  repository: https://charts.bitnami.com/bitnami
  version: 13.10.3
description: kubefirst helm chart
name: kubefirst
type: application
version: 2.3.2-rc0-alpha.96ae1d09
