console:
  domain: kubefirst.dev
global:
  kubefirst-api-eeVersion: v2.5.0-rc14
  kubefirst-apiVersion: v2.5.0-rc13
  kubefirstVersion: v2.4.17
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets
