mongodb:
  auth:
    existingSecret: kubefirst-initial-secrets
global:
#  kubefirstVersion: v2.2.14
  kubefirstVersion: development
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets
kubefirst-api:
  env:
  - name: "CLOUD_PROVIDER"
    value: "<CLOUD_PROVIDER>"
