console:
  domain: kubefirst.dev
global:
  consoleVersion: v2.5.10-rc3
  kubefirst-api-eeVersion: v2.5.9-rc3
  kubefirst-apiVersion: v2.5.10-rc2
  kubefirstVersion: v2.5.10
kubefirst-api-ee:
  existingSecret: kubefirst-initial-secrets
