name: Release Charts

on:
  release:
    types: [created]

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Push Helm Chart to ChartMuseum
        uses: bsord/helm-push@v4.1.0
        with:
          username: '${{ secrets.CHARTMUSEUM_USER }}'
          password: ${{ secrets.CHARTMUSEUM_PASSWORD }}
          registry-url: 'https://charts.kubefirst.com'
          chart-folder: charts/kubefirst
          update-dependencies: true
          force: true
