name: Release Charts

on:
  push:
    branches:
      - publish

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: "${{ secrets.GH_TOKEN }}"
          charts_url: https://kubefirst.github.io
          repository: charts