name: Release Charts

on:
  push:
    branches:
      - publish

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Publish Helm chart
        uses: goodsmileduck/helm-push-action@v2
        env:
          SOURCE_DIR: './charts'
          CHART_FOLDER: "${GITHUB_REPOSITORY_NAME_PART}"
          FORCE: 'True'
          CHARTMUSEUM_URL: 'https://charts.kubefirst.com'
          CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
          CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}